// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYtxZDRG3B6uYny6URHcAp9B4cf2mRH9Q',
    appId: '1:463003406902:web:ac2758f792b908acd23e97',
    messagingSenderId: '463003406902',
    projectId: 'posd-c38d4',
    authDomain: 'posd-c38d4.firebaseapp.com',
    storageBucket: 'posd-c38d4.firebasestorage.app',
    measurementId: 'G-JCHF0MNC36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOFVKhGcPjcAtUOBKRHTd5MJYEwrLvrbg',
    appId: '1:463003406902:android:061cba07531a08bbd23e97',
    messagingSenderId: '463003406902',
    projectId: 'posd-c38d4',
    storageBucket: 'posd-c38d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL3-rIfvC1EAewOHuWx3STP-1tC0U8CtA',
    appId: '1:463003406902:ios:bbadafe6e1d3d9e6d23e97',
    messagingSenderId: '463003406902',
    projectId: 'posd-c38d4',
    storageBucket: 'posd-c38d4.firebasestorage.app',
    iosBundleId: 'com.example.pos',
  );
}
